#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH_PATTERN="^(feature|fix|hotfix)\/[a-z0-9-_]+$"
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if ! [[ "$BRANCH_NAME" =~ $BRANCH_PATTERN ]]; then
  echo "🚫 Invalid branch name: '$BRANCH_NAME'"
  echo "Branch names must follow the pattern: 'feature/<description>', 'fix/<description>', or 'hotfix/<description>'."
  exit 1
fi

echo "✅ Branch name is valid!"
