#!/bin/bash
email="your-email@example.com"
regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

if [[ $email =~ $regex ]]; then
  echo "The email ($email) is valid."
else
  echo "The email ($email) is invalid."
fi